Allow two optimization test to pass
sherpa/sherpa pull request #1088
Opened 2021-01-29 16:29 UTC by DougBurke

# Summary

Address an issue in the optimization tests that meant two tests were failing. This only changes the test code and makes no change to the behavior of the optimizers.

# Details

In #1084 I noted that an optimization test (`penaltyII`) that was marked as xfail could occasionally pass. I've tracked it down to a problem with the initialization code for the test (and another test) which had the `mpar` size set to `65` rather than `2 * npar`. I would guess this was a cut-n-paste error as it also affected the `powell (badly scaled)` test.

I did a quick scan for other tests that fail for some, not all, optimizers but it's not easy. For instance the  Meyer test is "interesting"; it has `npar=3` but the `Mayer` routine only ever seems to use `x[ii]` with `ii=0` (unlike I'm caffeine induced).

https://github.com/sherpa/sherpa/blob/master/sherpa/optmethods/tests/tstoptfct.hh#L2076-L2112

2021-01-29 23:03 UTC, dtnguyen2 commented
Sure enough the tests now pass, using LevMar:

```
(sherpa) [dtn@devel12 minpack]$ grep g++ LevMar.cc
g++ -ansi -pedantic -Wall -O3 -I. -I../../../include -I../.. -DtestLevMar -DNDEBUG LevMar.cc -o levmar(sherpa) [dtn@devel12 minpack]$ valgrind levmar | grep PenaltyII
==10459== Memcheck, a memory error detector
==10459== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==10459== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==10459== Command: levmar
==10459== 
lmdif_PenaltyII	514	9.37629e-06	9.37903e-06	0.199999,0.215019,0.467088,0.514755	1,1757.2,1771.19,2236.35
==10459== 
==10459== HEAP SUMMARY:
==10459==     in use at exit: 0 bytes in 0 blocks
==10459==   total heap usage: 345 allocs, 345 frees, 115,024 bytes allocated
==10459== 
==10459== All heap blocks were freed -- no leaks are possible
==10459== 
==10459== For counts of detected and suppressed errors, rerun with: -v
==10459== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

Using NelderMead:
```
(sherpa) [dtn@devel12 src]$ grep g++ NelderMead.cc
g++  -ansi -pedantic -Wall -O3 -I. -I../../include -I.. -DtestNelderMead -DNDEBUG NelderMead.cc Simplex.cc -o neldermead
(sherpa) [dtn@devel12 src]$ g++  -ansi -pedantic -Wall -O3 -I. -I../../include -I.. -DtestNelderMead -DNDEBUG NelderMead.cc Simplex.cc -o neldermead
(sherpa) [dtn@devel12 src]$ valgrind neldermead | grep PenaltyII
==10569== Memcheck, a memory error detector
==10569== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==10569== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==10569== Command: neldermead
==10569== 
NelderMead_0_0_PenaltyII	1531	9.37629e-06	9.51886e-06	0.199972,0.235897,0.5592,0.218371
NelderMead_1_0_PenaltyII	149	9.37629e-06	9.45514e-06	0.200003,0.272851,0.346956,0.613102
NelderMead_0_1_PenaltyII	3185	9.37629e-06	9.37663e-06	0.199997,0.195042,0.484442,0.506477
NelderMead_1_1_PenaltyII	1239	9.37629e-06	9.39556e-06	0.199999,0.25432,0.460263,0.471467
NelderMead_0_2_PenaltyII	3520	9.37629e-06	9.37631e-06	0.199999,0.193005,0.47917,0.518691
NelderMead_1_2_PenaltyII	2387	9.37629e-06	9.37629e-06	0.199999,0.191318,0.480113,0.518823
==10569== 
==10569== HEAP SUMMARY:
==10569==     in use at exit: 0 bytes in 0 blocks
==10569==   total heap usage: 206,016 allocs, 206,016 frees, 27,406,656 bytes allocated
==10569== 
==10569== All heap blocks were freed -- no leaks are possible
==10569== 
==10569== For counts of detected and suppressed errors, rerun with: -v
==10569== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
Using DifEvo:
```
(sherpa) [dtn@devel12 src]$ g++  -ansi -pedantic -Wall -O3 -I. -I../../include -I.. -DtestDifEvo -DNDEBUG DifEvo.cc Simplex.cc -o difevo
(sherpa) [dtn@devel12 src]$ valgrind difevo | grep PenaltyII
==10750== Memcheck, a memory error detector
==10750== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==10750== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==10750== Command: difevo
==10750==
DifEvo_nm_PenaltyII	790	9.37629e-06	9.38448e-06	0.200008,0.148759,0.50296,0.517361
DifEvo_PenaltyII	-3609	9.37629e-06	2.34001	0.5,0.5,0.5,0.5
DifEvo_lm_PenaltyII	585	9.37629e-06	9.37629e-06	0.199999,0.191382,0.480075,0.518822
==10750== 
==10750== HEAP SUMMARY:
==10750==     in use at exit: 0 bytes in 0 blocks
==10750==   total heap usage: 918,471 allocs, 918,471 frees, 156,994,792 bytes allocated
==10750== 
==10750== All heap blocks were freed -- no leaks are possible
==10750== 
==10750== For counts of detected and suppressed errors, rerun with: -v
==10750== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0) 
```

2021-01-29 23:03 UTC, dtnguyen2 approved these changes

2021-01-29 23:04 UTC, dtnguyen2 commented
sorry, I accidentally hit the _Close with comment_ icon

2021-01-29 23:10 UTC, dtnguyen2 requested changes
Sorry, I was a bit overzealous in approving the PR.  I looked over the paper titled: [Testing Unconstrained Optimization Software](https://www.osti.gov/servlets/purl/6650344).  The initial parameters should be at ```(0.5, 0.5, ..., 0.5)``` and ```mfct=2*npar```

(sherpa) [dtn@devel12 sherpa]$ git status
On branch DougBurke-penaltyii
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   sherpa/optmethods/tests/tstoptfct.hh

no changes added to commit (use "git add" and/or "git commit -a")
(sherpa) [dtn@devel12 sherpa]$ git diff sherpa/optmethods/tests/tstoptfct.hh
diff --git a/sherpa/optmethods/tests/tstoptfct.hh b/sherpa/optmethods/tests/tstoptfct.hh
index 3ee65983..6e052bf4 100644
--- a/sherpa/optmethods/tests/tstoptfct.hh
+++ b/sherpa/optmethods/tests/tstoptfct.hh
@@ -2347,9 +2347,9 @@ namespace tstoptfct {
     if ( 4 != npar )
       throw std::runtime_error( "npar for the PenaltyI func must be 4\n" );
 
-    mfct = npar + 1;
+    mfct = 2 * npar;
     for ( int ii = 0; ii < npar; ++ii )
-      x[ ii ] = ii + 1;
+      x[ ii ] = 0.5;
 
     for ( int ii = 0; ii < npar; ++ii )
       lo[ ii ] = -1.0e6;

2021-01-30 04:21 UTC, DougBurke commented
@dtnguyen2 - this is for PenaltyI which I haven't touched - ie you are looking at `PenaltyIInit` and not `PenaltyIIInit` (the names are confusing and took me time to work out when I was trying to diagnose this).

We can add it here, but I just wanted to check that it's changing the right function.

2021-01-30 13:47 UTC, DougBurke commented
From page 19 of https://www.osti.gov/servlets/purl/6650344 I think the PenaltyI test has the right initialisation for the starting point - it depends on whether `x_0 = e_j where e_j = j` has j = [1, 2, ..] or j = [0, 1, ...] - and also it has `m = n + 1` which I guess translates to the `mfct = npar + 1` setting.

**HOWEVER** I think it has the wrong best-fit value

```
In [1]: from sherpa.optmethods import _tstoptfct

In [2]: _tstoptfct.init('penaltyI', 4)
Out[2]:
(array([1., 2., 3., 4.]),
 array([-1000000., -1000000., -1000000., -1000000.]),
 array([1000000., 1000000., 1000000., 1000000.]),
 9.37629e-06)

In [3]: _tstoptfct.init('penaltyII', 4)
Out[3]:
(array([0.5, 0.5, 0.5, 0.5]),
 array([-1000000., -1000000., -1000000., -1000000.]),
 array([1000000., 1000000., 1000000., 1000000.]),
 9.37629e-06)
```

They both report 9.37629e-6 but that's the penaltyII value; the penaltyI value should have

    n = 4   -> 2.24997e-5

I don't think we're set up to test the n=10 case - e.g.

```
In [4]: _tstoptfct.init('penaltyI', 10)
terminate called after throwing an instance of 'std::runtime_error'
  what():  npar for the PenaltyI func must be 4

Aborted (core dumped)
```

2021-01-30 13:54 UTC, DougBurke commented
I've just checked and the test for penaltyI passes if I change PenaltyIInit to

    // answer = 9.37629e-6; // I think this is wrong
    answer = 2.24997e-5;

which is presumably because we have an absolute tolerance difference of 1e-3 for the check. This may have been a by-product of changing from the previous test style to using pytest.approx?

I wonder if we should test the log(10) value of the statistic in these tests, then we can hopefully tighten up the tolerances.

2021-01-30 14:22 UTC, dtnguyen2 commented
You are right that I mixed up with the ```PenaltyIInit``` and ```PenaltyIIInit```, if only I could blame it on my bad handwriting.

If you are interested in checking for the case n == 10, then the following code (untested, but I think it will work):
```
template<typename Real>
  void PenaltyIInit( int npar, int& mfct, Real& answer, Real* x,
                     Real* lo, Real* hi ) {

    if ( 4 != npar || 10 != npar )
      throw std::runtime_error( "npar for the PenaltyI func must be 4 or 10\n" );

    mfct = npar + 1;
    for ( int ii = 0; ii < npar; ++ii )
      x[ ii ] = ii + 1;

    for ( int ii = 0; ii < npar; ++ii )
      lo[ ii ] = -1.0e6;

    for ( int ii = 0; ii < npar; ++ii )
      hi[ ii ] = 1.0e6;

    switch(npar) {
    case 4:
      answer = 2.24997e-5;
      break;
    case 10:
      answer = 7.08765e-5;
      break;
    }
  }
```

As for your comment:

> I wonder if we should test the log(10) value of the statistic in these tests, then we can hopefully tighten up the tolerances. Of course, we have a number of tests where the minimum value is <= 0, which complicates things a bit.

There are so many theories of how to test two numbers are close.  For example, ```sao_fcmp``` piggy back off the ```_gsl_fcmp``` function.  BTW, sherpa also ships with the function ```Knuth_close```, which can be found in the file _sherpa/utils/__init__.py_, is a Python implementation of the algorithm as outlined in [Theory behind floating point comparisons](https://www.boost.org/doc/libs/1_61_0/libs/test/doc/html/boost_test/testing_tools/extended_comparison/floating_point/floating_points_comparison_theory.html). Choose your poison.

2021-01-30 16:09 UTC, DougBurke commented
I'm not really looking to learn the ins and outs of the optimization testing today, so I don't plan to make any more changes to this (other than needed to get it accepted).

2021-01-30 19:13 UTC, dtnguyen2 approved these changes

2021-02-02 13:25 UTC, merged