Internal clean up of estmethods
sherpa/sherpa pull request #1773
Opened 2023-05-19 13:13 UTC by DougBurke

# Summary

Code clean up of sherpa.estmethods.

# Details

This is clean-up code which I've pulled out of https://github.com/sherpa/sherpa/pull/1735

These changes are driven by pylint, and involve the following, but note [*]

- use of f-strings (although there are plenty of strings that could be converted, the test coverage of these other lines is poor [*] so I don't want to make changes that could break things)
- using modern Python idioms, like
  - do not create a `__init__` call that just calls the superclass
  - do not have `if/elif/.../else` chains when each branch ends in a return or an exception
  - "re-raise" exceptions via "from" to make tracebacks cleaner
  - avoid un-needed brackets
  - use things like "min(xs, val)" and "a < 23" to avoid a "if/then" call
- I have also removed some `__str__` and `__repr__` mehods that were only ever really neded for development/testing (including at least one mis-spelled `__rep__` case)

There's a lot more changes that could be made - this code appears to be written in a Java/C++ style and so uses names like `dir` and `iter` that shadow existing functionality - but I do not want to make the changes too extensive at this time (as I don't plan to be changing this code anytime soon, if ever).

There are some changes that could be made but they will be made either as part of #1735 or some other PR (in particular changes to the parallel code).

[*] coverage is low in part because there's a lot of code written to handle exceptional circumstances (such as finding a better fit during the error analysis, or handling of semi-open intervals, which are hard to find test cases for)

2023-05-24 20:04 UTC, DougBurke commented on sherpa/estmethods/tests/test_estmethods.py
> +    print(str(m))
```suggestion
```

2023-05-24 20:54 UTC, DougBurke commented
Sorry @hamogu - this one isn't particularly interesting and it doesn't obviously improve anything. It's just clean-up I noticed when working in #1735. This is not really code I want to work on, so I am trying not to make too many changes, in particular because the test coverage isn't great, and trying to find tests that can improve this coverage is hard, as it deals with a lot of edge cases when calculating errors, which are not easy to create from first principles...

2023-05-25 10:40 UTC, hamogu requested changes
@DougBurke I appreciate these seemingly small clean-ups. We don't want to be changing code just for the sake of changing code; but when we (you much more often than I do) go spelunking into Sherpa's bowls, it helps to find code that's somewhat clean an readable so that I can understand the behavior I'm looking for quickly and go back to my original problem.

I agree with your assessment to do some simple changes while looking at it and leave comments (TODO) for other things that turn up but are not addressed now.

Could be merged as is, but since I reviewed it anyway, one suggestion that cuts another few lines and level of indentation to make the intend of the code more clear.

2023-05-25 10:40 UTC, hamogu commented on sherpa/estmethods/__init__.py
> +                return (xb, xa)
```suggestion
                return min(xa, xb), max(xa, xb)
```

2023-05-25 15:10 UTC, hamogu approved these changes

2023-05-25 15:30 UTC, merged