Opt cleanup
sherpa/sherpa pull request #2047
Opened 2024-05-22 13:18 UTC by DougBurke

WIP

# Details

This is a follow-on to #2045 and takes in some of the changes in #2015. However, there is less of an attempt to mark symbols as deprecated as these are definitely internal routines for this module. Much of the code removal is to remove debugging information that only someone who could edit the code could get to see. This, along with some typing annotation, and some understanding of the code from #2007 / #2022, has lead to some minor code cleanups.

I have added some notes of possible future work (none of them would be significant changes), but it's hard to make these changes as those code paths are currently not tested.

2024-08-02 03:04 UTC, DougBurke commented
Rebased as I try to make `sherpa.utils.types` a thing.

2024-09-09 12:59 UTC, DougBurke commented
Rebased to pick up recent changes and re-ordered the commits.

2025-01-03 21:30 UTC, DougBurke commented
Rebased and took the time to change `Optional[xxx]` to `xxx | None` as we no longer need to support python 3.9.

2025-01-10 19:34 UTC, DougBurke commented
Rebased as #2207 has been merged. I have also extracted out a `Callback` class to go with the `InfinitePotential` class: these could

- have a more-sensible naming scheme
- be arranged into a hierarchy

but for now I'm not sure this would provide any benefit.

2025-01-17 16:06 UTC, DougBurke commented
Rebased to pick up #2208

2025-01-21 17:19 UTC, hamogu requested changes

2025-01-21 17:19 UTC, hamogu commented on sherpa/optmethods/optfcts.py
> +    return out
This function is unnecessary. Numpy itself allows `low` and `high` argument in the random number generators to be arrays already. Remove this function and inline the lumpy call directly where needed:
```Python
rand_start = random.uniform(rng, xmin, xmax)
```

Performance will be better (no Python loop), but more importantly, the code it easier to understand because it avoids an extra level of indirection.

2025-01-21 17:20 UTC, hamogu commented on sherpa/optmethods/optfcts.py
> +    return out
I know this function was there before, but sine this commit touches it, it might as well remove it altogether. I checked the docs back to lumpy 1.20 and at least the far `low` and `high` can be arrays.

2025-01-21 17:53 UTC, DougBurke commented on sherpa/optmethods/optfcts.py
> +    return out
Note that `random.uniform` is actually `sherpa.utils.random.uniform`. Now, we can do what we like with this routine, but it just needs some work to check.

For reference, this routine will take the `rng` argument and do something sensible if `rng` is `None`.

2025-01-21 18:49 UTC, hamogu commented on sherpa/optmethods/optfcts.py
> +    return out
It should just pass through the arrays, because `sherpa.utils.random.uniform` call numpy in both cases and will just do the right thing: https://github.com/sherpa/sherpa/blob/main/sherpa/utils/random.py#L188

2025-01-21 18:49 UTC, hamogu commented on sherpa/optmethods/optfcts.py
> +    return out
Which will means tat tis function is not needed, `just all sherpa.utils.random.uniform` directly.

2025-01-24 15:44 UTC, DougBurke commented
@hamogu - one thing I'm interested in is the "best" way to change local callbacks, where we previously defined a symbol within a routine like

```python
    # fcn is an argument to the enclosing function
    def cb(x):
        return fcn(x)[0]
```

to a new class-based system, like

```python
class Callback:
    def __init__(self, fcn):
        self.fcn = fcn

    def __call__(self, x):
        return self.fcn(x)[0]
```

where we then cam just say (in the function)

```python
    cb = Callback(fcn)
```


I have been doing this because the local callbacks seem to cause an issue for `multiprocessing` when using non-`fork` methods - for more information see #2007 - but I wonder if there's other ways we should do this? The best I could think of was a decorator, but I don't think it would save complexity (but I haven't tried to get it to work). I think most of these classes are going to be local to the module (although I have put some somewhere in `sherpa.utils` in my experiments) so I think it's okay (i.e. this complexity is "hidden within" the module).

2025-01-30 19:57 UTC, hamogu commented
Effectively, what you are doing here is to define a protocol. `Callback` is one function that implements that protocol, `InfinitePotential` is the other. They are not derived in a hierarchy, but they have the same call signatures for `__init__` and `__call__` (including the same statement `return self.func(pars)[0]`).

Since you are into typing, you of course have the [option to make the definition explicit for static type checking)](https://typing.readthedocs.io/en/latest/spec/protocol.html#protocols) (not sure about the Python version where this becomes available), but as far as Python itself is concerned when running, it's just Duck-typing.

Any other class that follows that definition could also be used in it's place (for example, I have long wanted to make a "Not-quite infinite potential" because I noted that some optimizers get stuck one they hit the infinite part, instead, I think we should have a "sloped infinite potential" which returns "really_big_number + 1e4 * x" where "x" is the distance to the boundary where solutions are valid, to motivate the optimizer to move back into the valid region - see #835.

Of course, since the effect is so simple, a decorator would also work, but I don't think that would be easier to understand when reading the code, nor would it be noticeably faster when running. So, I think classes are good.

2025-02-10 16:43 UTC, DougBurke commented on sherpa/optmethods/optfcts.py
> +    return out
I've removed this routine (and added a test just to show that `sherpa.utils.random.uniform` is doing the right thing).

There's a 50/50 chance the tests will fail because of some other recent change to OTS packages ....

2025-02-13 18:37 UTC, DougBurke commented on sherpa/optmethods/optfcts.py
> +    return out
@hamogu - is this change okay?

2025-02-13 19:00 UTC, hamogu approved these changes

2025-02-13 19:05 UTC, wmclaugh commented on sherpa/optmethods/__init__.py
> +    so can specific to the optimization function. The x0, xmin, and
```suggestion
    so can be specific to the optimization function. The x0, xmin, and
```

2025-02-19 20:04 UTC, DougBurke commented
@wmclaugh - are you waiting for anything more for this PR?

2025-02-19 20:52 UTC, wmclaugh commented on sherpa/utils/tests/test_random.py
> +    The behaviour tested here is disussed in
```suggestion
    The behaviour tested here is discussed in
```

2025-02-20 13:36 UTC, merged