Change the URL for XPA
sherpa/sherpa pull request #2102
Opened 2024-08-15 13:05 UTC by DougBurke

# Summary

Change the URL used for XPA. Fix #2100.

# Details

As XPA development has stopped, the old SAO page is no longer available, so change to use the GitHub URL (less information, but it is at least valid).

2024-08-15 23:17 UTC, anetasie requested changes
The new XPA link works, but there is another link on line 139 to the packages goes to error page: https://packages.ubuntu.com/xenial/xpa-tools

Is there another link which would work here?

2024-08-16 11:52 UTC, DougBurke commented
Argh. So, there's no "stable" link (that I know of) for a Ubuntu package, since they want them versioned by the Ubuntu release (makes sense). So it's easiest just to remove the link.

2024-08-16 12:19 UTC, anetasie commented
I just approved this PR,

2024-08-16 12:28 UTC, DougBurke commented
Ta - Duog

On Fri, Aug 16, 2024 at 8:19 AM Aneta Siemiginowska <
***@***.***> wrote:

> I just approved this PR,
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sherpa/sherpa/pull/2102#issuecomment-2293407885>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABW27SSDIWLDSZJHUIW4LDZRXU5VAVCNFSM6AAAAABMSFP76SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJTGQYDOOBYGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-16 15:49 UTC, merged