Add models from XSPEC 12.14.1
sherpa/sherpa pull request #2116
Opened 2024-08-27 02:39 UTC by DougBurke

# Summary

Add models from XSPEC 12.14.1 and change the parameter settings to match those from 12.14.1, where necessary.

# Details

We do not need any changes to build against 12.14.1, which is nice, but there are new models we can provide.

I have reported two issues to the XSPEC  with 12.14.1

- `ismabs` seems to crash
- the new `sssed` model has an invalid `frac_th` parameter settings in `model.dat`; I have used what I believe to make sense but until we get a patch release out we can't guarantee I've got it right.

2024-08-30 15:57 UTC, DougBurke commented
Rebased to pick up

- #1793 

It didn't conflict but I wanted to make sure we were using the new code.

2024-09-17 14:21 UTC, wmclaugh commented on scripts/check_xspec_update.py
> +        Do we bother checking the limits for the swich parameter
```suggestion
        Do we bother checking the limits for the switch parameter
```

2024-09-17 15:01 UTC, DougBurke commented on scripts/check_xspec_update.py
> +        Do we bother checking the limits for the swich parameter
Argh.

2024-09-25 20:38 UTC, anetasie commented
@DougBurke @wmclaugh I don't remember what XSPEC version we were planning to support for this release. Are we planning to take this PR?

2024-09-25 20:44 UTC, DougBurke commented
@anetasie - CIAO 4.17 will use XSPEC 12.14.0something, not 12.14.1.

If we do not take this PR then users can still build with 12.14.1, they just won't get the new models (this is not always true, but fortunately is in this case). So while it is not ideal, it is not a deal breaker (the new models appear to generally be XRISM-related with making it easier to get widths of lines in km/s rather than energy, so again not what I would claim are generally important).

2025-01-08 20:04 UTC, DougBurke commented
Rebased to pick up recent changes.

2025-02-13 18:43 UTC, DougBurke commented
Rebased as #2215 has been merged (there was no conflict but I just wanted to make sure everything was up to date).

2025-02-13 22:17 UTC, DougBurke commented on sherpa/astro/xspec/__init__.py
> +    .. versionchanged:: 4.17.0
argh - need to update the version number

2025-02-13 22:18 UTC, DougBurke commented on sherpa/astro/xspec/__init__.py
> +    .. versionadded:: 4.17.0
bump version number

2025-02-13 22:19 UTC, DougBurke commented on sherpa/astro/xspec/__init__.py
> +
Need a `versionadded` comment, I htink

2025-02-19 20:03 UTC, DougBurke commented
@hamogu - do you have time to quickly check the python parts of this? It is a relatively-straightforward upgrade so I don't see it being too problematic, but it is too easy to get into a "this is obviously correct" mindset when making this sort of a change!

2025-02-21 22:30 UTC, hamogu requested changes
It never amazes me how XSPEC adds new models that look all the same (e.g. absorption with with z=0 fixed vs. z variable). I'm sure they have good reasons...but that's not for us to litigate; we simply take what they offer.

2025-02-21 22:30 UTC, hamogu commented on sherpa/astro/xspec/tests/test_xspec.py
> +XSPEC_MODELS_COUNT = 289
We went from 28 to 289 models?
```suggestion
XSPEC_MODELS_COUNT = 29
```

2025-02-21 22:51 UTC, DougBurke commented on sherpa/astro/xspec/tests/test_xspec.py
> +XSPEC_MODELS_COUNT = 289
Errr, no. We went from 281 to 289 models. As the code originally said.

2025-02-21 23:19 UTC, hamogu commented on sherpa/astro/xspec/tests/test_xspec.py
> +XSPEC_MODELS_COUNT = 289
Oh wow. That's a lot of models!

2025-02-21 23:19 UTC, hamogu approved these changes

2025-02-24 19:22 UTC, DougBurke commented on sherpa/astro/xspec/tests/test_xspec.py
> +XSPEC_MODELS_COUNT = 289
For reference, in CIAO 4.17 (which only supports models up to 12.14.0) we have

```
sherpa In [3]: len(list_models("xspec"))
Out[3]: 281

sherpa In [4]: list_models("xspec")[0:5]
Out[4]: ['xsabsori', 'xsacisabs', 'xsagauss', 'xsagnsed', 'xsagnslim']

sherpa In [5]: from sherpa.astro import xspec

sherpa In [6]: xspec.get_xsversion()
Out[6]: '12.14.0k'

```

2025-02-26 13:14 UTC, merged