updated the front page of Sherpa RTD with references
sherpa/sherpa pull request #2153
Opened 2024-09-23 20:14 UTC by anetasie

I included the references to the three papers on the front page of Sherpa documentation.

2024-09-23 20:37 UTC, DougBurke commented
Does anything need to get added to https://github.com/sherpa/sherpa/blob/main/README.md ?

2024-09-23 21:24 UTC, anetasie commented
@DougBurke update README in #2154

2024-09-23 22:50 UTC, hamogu requested changes

2024-09-23 22:50 UTC, hamogu commented on docs/index.rst
> +`Sherpa Paper 2001 <https://arxiv.org/abs/astro-ph/0108426>`_ (`ADS BibTex <https://ui.adsabs.harvard.edu/abs/2001SPIE.4477...76F/exportcitation>`_)
The readthedocs build fails with 
```
/home/docs/checkouts/readthedocs.org/user_builds/sherpa/checkouts/2153/docs/index.rst:47: WARNING: Duplicate explicit target name: "ads bibtex".
/home/docs/checkouts/readthedocs.org/user_builds/sherpa/checkouts/2153/docs/index.rst:47: WARNING: Duplicate explicit target name: "ads bibtex".
```

I think (but did not test) that making the anonymous links (without an explicit entry in sphinx directory of targets shuld work):
```suggestion
`Sherpa Paper 2024 <https://arxiv.org/abs/2409.10400>`_ (`ADS BibTex <https://ui.adsabs.harvard.edu/abs/2024arXiv240910400S/exportcitation>`__)

`Sherpa Paper 2007 <https://articles.adsabs.harvard.edu/full/2007ASPC..376..543D>`_ (`ADS BibTex <https://ui.adsabs.harvard.edu/abs/2007ASPC..376..543D/exportcitation>`__)

`Sherpa Paper 2001 <https://arxiv.org/abs/astro-ph/0108426>`_ (`ADS BibTex <https://ui.adsabs.harvard.edu/abs/2001SPIE.4477...76F/exportcitation>`__)
```

2024-09-23 23:34 UTC, anetasie commented
@hamogu it worked and the RTD page looks good.

2024-09-24 11:12 UTC, hamogu approved these changes

2024-09-24 13:51 UTC, merged